jwt:
  secret: birllMonstrao
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user-service/**
      - id: company-service
        uri: lb://company-service
        predicates:
        - Path=/company-service/**
      - id: exercise-service
        uri: lb://exercise-service
        predicates:
        - Path=/exercise-service/**
      - id: workout-service
        uri: lb://workout-service
        predicates:
        - Path=/workout-service/**
      - id: workout-sheet-service
        uri: lb://workout-sheet-service
        predicates:
        - Path=/workout-sheet-service/**
      - id: openapi
        uri: lb://gateway-server
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: rabbit
springdoc:
  swagger-ui:
    urls:
    - name: user-service
      url: /v3/api-docs/user-service
    - name: company-service
      url: /v3/api-docs/company-service
    - name: exercise-service
      url: /v3/api-docs/exercise-service
    - name: workout-service
      url: /v3/api-docs/workout-service
    - name: workout-sheet-service
      url: /v3/api-docs/workout-sheet-service