server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: empresa-service
        uri: lb://empresa-service
        predicates:
        - Path=/empresa-service/**
      - id: usuario-servive
        uri: lb://usuario-service
        predicates:
        - Path=/usuario-service/**