jwt:
  secret: birllMonstrao
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
            - Path=/user-service/**
        filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs
      - id: gender-service
        uri: lb://user-service
        predicates:
            - Path=/gender-service/**
        filters:
            - RewritePath=/gender-service/v3/api-docs, /v3/api-docs
      - id: authorization-service
        uri: lb://user-service
        predicates:
            - Path=/authorization-service/**
        filters:
            - RewritePath=/authorization-service/v3/api-docs, /v3/api-docs
      - id: company-service
        uri: lb://company-service
        predicates:
           - Path=/company-service/**
        filters:
           - RewritePath=/company-service/v3/api-docs, /v3/api-docs
      - id: exercise-service
        uri: lb://exercise-service
        predicates:
           - Path=/exercise-service/**
        filters:
           - RewritePath=/exercise-service/v3/api-docs, /v3/api-docs
      - id: muscleGroup-service
        uri: lb://exercise-service
        predicates:
           - Path=/muscleGroup-service/**
        filters:
           - RewritePath=/muscleGroup-service/v3/api-docs, /v3/api-docs
      - id: executed-workout-service
        uri: lb://executed-workout-service
        predicates:
           - Path=/executed-workout-service/**
        filters:
           - RewritePath=/executed-workout-service/v3/api-docs, /v3/api-docs
      - id: workout-sheet-service
        uri: lb://workout-sheet-service
        predicates:
           - Path=/workout-sheet-service/**
        filters:
           - RewritePath=/workout-sheet-service/v3/api-docs, /v3/api-docs
      - id: openapi
        uri: lb://gateway-server
        predicates:
           - Path=/v3/api-docs/**
        filters:
           - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: rabbit
springdoc:
  swagger-ui:
    urls:
    - name: user-service
      url: /v3/api-docs/user-service
    - name: company-service
      url: /v3/api-docs/company-service
    - name: exercise-service
      url: /v3/api-docs/exercise-service
    - name: executed-workout-service
      url: /v3/api-docs/executed-workout-service
    - name: workout-sheet-service
      url: /v3/api-docs/workout-sheet-service