version: '3.2'
services:
  usuario-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-usuario:/var/lib/postgresql/data
    command: -p 5434
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-usuario
    ports: 
      - 5434:5434
    expose:
      - 5434
    networks:
      - maromba-network
  empresa-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-empresa:/var/lib/postgresql/data
    command: -p 5433
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-empresa
    ports: 
      - 5433:5433
    expose:
      - 5433
    networks:
      - maromba-network
  movimento-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-movimento:/var/lib/postgresql/data
    command: -p 5435
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-movimento
    ports: 
      - 5435:5435
    expose:
      - 5435
    networks:
      - maromba-network
  exercicio-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-exercicio:/var/lib/postgresql/data
    command: -p 5436
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-exercicio
    ports: 
      - 5436:5436
    expose:
      - 5436
    networks:
      - maromba-network
  grupoMuscular-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-grupoMuscular:/var/lib/postgresql/data
    command: -p 5437
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-grupoMuscular
    ports: 
      - 5437:5437
    expose:
      - 5437
    networks:
      - maromba-network
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports: 
      - 9000:80
    networks:
      - maromba-network
    depends_on: 
      - usuario-db
      - empresa-db
      - movimento-db
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - maromba-network
  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: on-failure
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - maromba-network
  eureka-server:
    image: yurileao/maromba/backend/eureka-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - maromba-network
  usuario-service:
    image: yurileao/maromba/backend/usuario-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: usuario-service/Dockerfile
    links:
      - usuario-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://usuario-db:5434/maromba-usuario?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRICAO: dev
    depends_on:
      - usuario-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  empresa-service:
    image: yurileao/maromba/backend/empresa-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: empresa-service/Dockerfile
    links:
      - empresa-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://empresa-db:5433/maromba-empresa?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRICAO: dev
    depends_on:
      - empresa-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  movimento-service:
    image: yurileao/maromba/backend/movimento-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: movimento-service/Dockerfile
    links:
      - movimento-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://movimento-db:5435/maromba-movimento?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRICAO: dev
    depends_on:
      - movimento-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  exercicio-service:
    image: yurileao/maromba/backend/exercicio-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: exercicio-service/Dockerfile
    links:
      - exercicio-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://exercicio-db:5436/maromba-exercicio?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRICAO: dev
    depends_on:
      - exercicio-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  grupoMuscular-service:
    image: yurileao/maromba/backend/grupo-muscular-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: grupoMuscular-service/Dockerfile
    links:
      - grupoMuscular-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://grupoMuscular-db:5437/maromba-grupoMuscular?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRICAO: dev
    depends_on:
      - grupoMuscular-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  gateway-server:
    image: yurileao/maromba/backend/gateway-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: gateway-server/Dockerfile
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8765:8765
    depends_on:
      - rabbit-mq
      - eureka-server
      - usuario-service
      - empresa-service
    networks:
      - maromba-network
networks:
  maromba-network:
    driver: bridge