version: '3.2'
services:
  usuario-db:
    image: postgres:latest
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-usuario:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-usuario
    ports: 
      - 5432:5432
    expose:
      - 5432
    networks:
      - maromba-network
  empresa-db:
    image: postgres:latest
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-empresa:/var/lib/postgresql/data
    command: -p 5433
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-empresa
    ports: 
      - 5433:5433
    expose:
      - 5433
    networks:
      - maromba-network
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports: 
      - 9000:80
    networks:
      - maromba-network
    depends_on: 
      - usuario-db
      - empresa-db
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - maromba-network
  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: on-failure
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - maromba-network
  eureka-server:
    image: yurileao/maromba/backend/eureka-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - maromba-network
  gateway-server:
    image: yurileao/maromba/backend/gateway-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: gateway-server/Dockerfile
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8765:8765
    depends_on:
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  usuario-service:
    image: yurileao/maromba/backend/usuario-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: usuario-service/Dockerfile
    links:
      - usuario-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://usuario-db:5432/maromba-usuario?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
    ports: 
      - 8000:8000
    depends_on:
      - usuario-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
  empresa-service:
    image: yurileao/maromba/backend/empresa-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: empresa-service/Dockerfile
    links:
      - empresa-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://empresa-db:5433/maromba-empresa?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
    ports: 
      - 8100:8100
    depends_on:
      - empresa-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network
networks:
  maromba-network:
    driver: bridge