services:
  user-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-user:/var/lib/postgresql/data
    command: -p 5434
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-user
    ports: 
      - 5434:5434
    expose:
      - 5434
    networks:
      - maromba-network

  company-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-company:/var/lib/postgresql/data
    command: -p 5433
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-company
    ports: 
      - 5433:5433
    expose:
      - 5433
    networks:
      - maromba-network

  workout-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-workout:/var/lib/postgresql/data
    command: -p 5435
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-workout
    ports: 
      - 5435:5435
    expose:
      - 5435
    networks:
      - maromba-network

  exercise-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-exercise:/var/lib/postgresql/data
    command: -p 5436
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-exercise
    ports: 
      - 5436:5436
    expose:
      - 5436
    networks:
      - maromba-network

  workout-sheet-db:
    image: postgres:14.5
    restart: on-failure
    tty: true
    volumes: 
      - .pgdata/maromba-workout-sheet:/var/lib/postgresql/data
    command: -p 5437
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=maromba-workout-sheet
    ports: 
      - 5437:5437
    expose:
      - 5437
    networks:
      - maromba-network

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports: 
      - 9000:80
    networks:
      - maromba-network
    depends_on: 
      - user-db
      - company-db
      - workout-db
      - workout-sheet-db
      - exercise-db

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - maromba-network

  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: on-failure
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - maromba-network

  eureka-server:
    image: yurileao/maromba/backend/eureka-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - maromba-network

  user-service:
    image: yurileao/maromba/backend/user-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: user-service/Dockerfile
    links:
      - user-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://user-db:5434/maromba-user?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRIPTION: dev
    depends_on:
      - user-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network

  company-service:
    image: yurileao/maromba/backend/company-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: company-service/Dockerfile
    links:
      - company-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://company-db:5433/maromba-company?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRIPTION: dev
    depends_on:
      - company-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network

  workout-service:
    image: yurileao/maromba/backend/workout-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: workout-service/Dockerfile
    links:
      - workout-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://workout-db:5435/maromba-workout?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRIPTION: dev
    depends_on:
      - workout-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network

  exercise-service:
    image: yurileao/maromba/backend/exercise-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: exercise-service/Dockerfile
    links:
      - exercise-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://exercise-db:5436/maromba-exercise?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRIPTION: dev
    depends_on:
      - exercise-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network

  workout-sheet-service:
    image: yurileao/maromba/backend/workout-sheet-service:0.0.1-SNAPSHOT
    #restart: always
    build: 
      context: .
      dockerfile: workout-sheet-service/Dockerfile
    links:
      - workout-sheet-db
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:postgresql://workout-sheet-db:5437/maromba-workout-sheet?ssl=false&currentSchema=public
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: root
      SPRING.DATASOURCE.DRIVECLASSNAME: org.postgresql.Driver
      API.SERVER.URL: http://localhost:8765/
      API.SERVER.DESCRIPTION: dev
    depends_on:
      - workout-sheet-db
      - rabbit-mq
      - eureka-server
    networks:
      - maromba-network

  gateway-server:
    image: yurileao/maromba/backend/gateway-server:0.0.1-SNAPSHOT
    build: 
      context: .
      dockerfile: gateway-server/Dockerfile
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8765:8765
    depends_on:
      - rabbit-mq
      - eureka-server
      - user-service
      - company-service
    networks:
      - maromba-network
networks:
  maromba-network:
    driver: bridge