server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: login-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  datasource:
    url: jdbc:postgresql://192.168.1.12:7070/maromba_login?currentSchema=public
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  devtools:
    remote:
      secret: 123